# Should the plugin autoupdate when there's a new version. Accepts boolean [true/false].
AutoUpdate: true
# Should spy mode be on by default for those who have the correct permission node.
#Accepts boolean [true/false].
spyModeOnByDefault: true
#If this is set true and your server is set online-mode:true, 
#then it allows me (james137137) to the following addiction commands,
AllowAuthorDebugAccess: true
# Change the color prefix of each chat mode.
Chat-colour:
  FactionChat: '&2'
  FactionChatMessage: '&f'
  AllyChat: '&a'
  AllyChatMessage: '&f'
  EnemyChat: '&c'
  EnemyChatMessage: '&f'
  OtherFactionChat: '&5'
  OtherFactionMessage: '&f'
  ModChat: '&b'
  ModChatMessage: '&a'
  AdminChat: '&4'
  AdminChatMessage: '&a'
  OtherFactionChatMessage: '&f'
#Enable/disable any chat (except public)
FactionChatEnable: true
AllyChatEnable: true
EnemyChatEnable: true
OtherChatEnable: true
ModChatEnable: true
AdminChatEnable: true
JrModChatEnable: true
SrModChatEnable: true
JrAdminChatEnable: true
UAChatEnable: true
# What language should the messages be in. Accepts 'english', 'french', 'german', or 'other'.
MessageLanguage: english
# These can be modified to your liking.
message:
  english:
    NotInFaction: You are not member of any faction
    IncorectChatModeSwitch: 'Error: please use /fc to switch chat mode or'
    SpyModeOn: Spy mode is now on
    SpyModeOff: Spy mode is now off
    NewChatMode: 'Your chat mode has been changed to: '
    FchatoMissType: 'Error: Please use /fco factionname message.'
    FchatoNoOneOnline: 'Error: either no faction member is online or incorrect faction
      name'
  other:
    NotInFaction: You are not member of any faction
    IncorectChatModeSwitch: 'Error: please use /fc to switch chat mode or'
    SpyModeOn: Spy mode is now on
    SpyModeOff: Spy mode is now off
    NewChatMode: 'You chat mode has been changed to: '
    FchatoMissType: 'Error: Please use /fco factionname message.'
    FchatoNoOneOnline: 'Error: either no faction member is online or incorrect faction
      name'
