name: FactionChat
softdepend: [Factions]
main: com.james137137.FactionChat.FactionChat
version: 1.501
authors: [James Anderson]
commands:
  fchat:
    description: Main command to switch Chat Mode
    usage: /<command> [option]
    aliases: [fc]
  fchato:
    description: Send a message to any Factions
    usage: /<command> <FactionName> <Message> 
    aliases: [fco]
  fchatf:
    description: Send a Faction message
    usage: /<command> <Message> 
    aliases: [ff]
  fchata:
    description: Send a Ally message
    usage: /<command> <Message> 
    aliases: [fa]
  fchate:
    description: Send a Enemy message
    usage: /<command> <Message> 
    aliases: [fe]
  fchatad:
    description: Send a admin message
    usage: /<command> <Message> 
    aliases: [fad]
  fchatm:
    description: Send a moderator message
    usage: /<command> <Message> 
    aliases: [fm]
       
permissions:
  FactionChat.*:
    description: Gives access to all FactionChat commands
    children:
      FactionChat.spy: true
      FactionChat.AdminChat: true
      FactionChat.Update: true
      FactionChat.OtherChat: true
      FactionChat.EnemyChat: true
  FactionChat.OtherChat:
    description: Allows player to send messages to other Factions
    default: op
  FactionChat.EnemyChat:
    description: Allows player to use Enemy chat.
    default: op
  FactionChat.spy:
    description: Allows player to see all Faction and ally chat
    default: op
  FactionChat.JrModChat:
    description: Allows player to see and use JrModerator chat
    default: op
  FactionChat.ModChat:
    description: Allows player to see and use Moderator chat
    default: op
    children:
      FactionChat.JrModChat: true
  FactionChat.SrModChat:
    description: Allows player to see and use SrModerator chat
    default: op
    children:
      FactionChat.JrModChat: true
      FactionChat.ModChat: true
  FactionChat.JrAdminChat:
    description: Allows player to see and use Jradministrator chat
    default: op
    children:
      FactionChat.JrModChat: true
      FactionChat.ModChat: true
      FactionChat.SrModChat: true
  FactionChat.AdminChat:
    description: Allows player to see and use Administrator chat
    default: op
    children:
      FactionChat.JrModChat: true
      FactionChat.ModChat: true
      FactionChat.SrModChat: true
      FactionChat.JrAdminChat: true
  FactionChat.Update:
    description: Allows player to Check and update this plugin
    default: op
  FactionChat.Reload:
    description: Allows player to reload plugin
    default: op

  
     